module.exports = {
  rootDir: '.',
  testEnvironment: 'jsdom',
  clearMocks: true,
  setupFilesAfterEnv: ['<rootDir>/setupTests.js'],
  coveragePathIgnorePatterns: [
    '.*\\.d\\.ts',
    '/components/.*./index\\.ts',
    'jest.config.js',
    'webpack.*\\.js',
    './coverage',
    './public',
    '/test-utils',
    '/types',
    '/strings',
    '/utils',
    '/build',
    'assets',
    './functions/setup.js',
    '/redux',
  ],
  roots: ['<rootDir>'],
  modulePaths: ['<rootDir>'],
};
