name: Build

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g twilio-cli
      - run: twilio plugins:install @twilio-labs/plugin-flex
      - run: npm install
      - run: npm test