name: PR validator

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'assets/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'assets/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - run: npm test
